### ISSUE TITLE
Problema con las rutas

### ISSUE THREAD

**Issue by Rafaherrero** [ULL-ESIT-SYTW-1617/tareas-iniciales-rafadanipedro#4]
El GitBook no detecta bien las rutas una vez se incluyen el _book.json_

**Comment by DanielRamosAcosta** [comment]
Creo que es porque gitbook va a buscar el `book.json` en el directorio raíz, pero lo tenemos en el `txt`

**Comment by Rafaherrero** [comment]
No hago referencia a eso, puesto que lo hemos puesto tanto en el directorio raíz como en el txt, y el GitBook si que detecta el _book.json_ en el directorio raíz, el problema es que no entra a la carpeta txt a buscar los md con la opción structure
