### ISSUE TITLE
Problema con Gulp, GitBook y las rutas

### ISSUE THREAD

**Issue by Rafaherrero** [ULL-ESIT-SYTW-1617/tareas-iniciales-rafadanipedro#5]
Tras solucionar el problema anterior con las rutas de los archivos md del libro, ahora Gulp no reconoce adecuadamente la ruta de los mismos.

**Comment by DanielRamosAcosta** [comment]
Hay que cambiar el comando del [script de generación del gitbook](https://github.com/ULL-ESIT-SYTW-1617/tareas-iniciales-rafadanipedro/blob/master/scripts/generate-gitbook.js), que antes tenía puesto como parámetro que usase el directorio `txt`. Habría que poner que cogiese el nuevo `book.json`
