### ISSUE TITLE
Al hacer el build y deploy hace algo raro o a mi al menos

### ISSUE THREAD

**Issue by alu0100505078** [ULL-ESIT-SYTW-1617/tareas-iniciales-rafadanipedro#8]
@DanielRamosAcosta  @Rafaherrero  al realizar el build y el deploy, el gh-pages no lo hace como debería ya que no accede a los apartados que debería acceder. Y en el libro hace lo mismo. 
Sin embargo yo desde gitbook al darle leer al libro si lo hace correctamente. Tendríamos que mirarlo o decirme si en caso contrario solo me pasa a mi... >.<

**Comment by DanielRamosAcosta** [comment]
@alu0100505078 mira a ver si después de lo que tocamos en clase sigue funcionando mal o algo plis

**Comment by alu0100505078** [comment]
@DanielRamosAcosta posiblemente el fallo sea que en la rama gh-pages ya hay un directorio que se llama gitbook... por tanto a la hora de hacer deploy no se crea ese directorio y no funciona el gh-page. Lo que habria que hacer sería cambiarle el nombre y ponerlo distinto.
